# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NookureInventory Publish API

on:
  push:
    branches: [ master ]
jobs:
  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Seting up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        env:
          GRGIT_USER: "Angelillo15"
          GRGIT_PASS: ${{ secrets.TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew publish gitPublishPushAll